//! The capability table (AUD-29-32): what slates does today, where, with what limits, and the executable
//! acceptance tests that prove each row. The README's status table is rendered from this registry and
//! `cargo xtask check` refuses a README whose table differs from the rendering, a cited test that does not
//! exist, or one marked `#[ignore]` — so the published capability text cannot drift from the reviewed
//! evidence without the check failing. `cargo xtask capabilities --write` regenerates the README's table
//! after the registry changes. A row's status is a reviewed judgement, stated with its limits; the check makes
//! sure the evidence it cites stays real, not that the judgement is right.

use std::path::Path;

/// Format: the marker opening the rendered table in the README.
pub const BEGIN: &str =
  "<!-- capabilities:begin (generated by `cargo xtask capabilities --write`; do not edit) -->";
/// Format: the marker closing it.
pub const END: &str = "<!-- capabilities:end -->";

/// How far a capability works today.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Status {
  /// Works as described, proven by the cited tests.
  Works,
  /// Works within the stated limits, proven by the cited tests.
  Limited,
  /// Not built; the limits name the gap that tracks it.
  Owed,
}

impl Status {
  fn label(self) -> &'static str {
    match self {
      Status::Works => "works",
      Status::Limited => "limited",
      Status::Owed => "owed",
    }
  }
}

/// One acceptance test: the file, and the test's name as it is declared there (a Rust `fn`, a Python
/// `def`, or a Node `test('…')` title).
#[derive(Clone, Copy, Debug)]
pub struct Evidence {
  pub file: &'static str,
  pub test: &'static str,
}

/// One row of the table.
#[derive(Clone, Copy, Debug)]
pub struct Capability {
  pub name: &'static str,
  pub status: Status,
  pub r#where: &'static str,
  pub limits: &'static str,
  pub evidence: &'static [Evidence],
}

const fn ev(file: &'static str, test: &'static str) -> Evidence {
  Evidence { file, test }
}

/// The registry, reviewed 2026-10-01 against the tree and the gap ledger.
pub const CAPABILITIES: &[Capability] = &[
  Capability {
    name: "Volumes: create, snapshot, clone, resize, destroy (CLI and daemon)",
    status: Status::Works,
    r#where: "macOS, Linux; the daemon on Windows",
    limits: "—",
    evidence: &[
      ev(
        "crates/cli/tests/cli.rs",
        "the_anchor_supervises_a_daemon_the_verbs_answer_and_the_daemon_leaves_with_the_anchor",
      ),
      ev(
        "crates/server/tests/daemon.rs",
        "the_daemon_serves_the_lifecycle_verbs_exactly_once_with_leases_and_typed_refusals",
      ),
    ],
  },
  Capability {
    name: "Mount a volume with no privilege (`slates mount`)",
    status: Status::Works,
    r#where: "macOS (loopback NFS under `mount_nfs`)",
    limits: "—",
    evidence: &[ev(
      "crates/cli/tests/cli.rs",
      "slates_mount_establishes_a_real_kernel_mount_and_unmount_removes_it",
    )],
  },
  Capability {
    name: "Mount a volume on Linux",
    status: Status::Limited,
    r#where: "Linux",
    limits: "the daemon's NFS export, mounted by the kernel client as root; the FUSE bridge is not served by the daemon yet (AUD-29-64)",
    evidence: &[
      ev(
        "crates/server/tests/nfs_v4_kernel.rs",
        "the_linux_kernel_nfsv4_client_mounts_and_works_a_volume",
      ),
      ev(
        "crates/server/tests/nfs_mount.rs",
        "the_daemon_serves_a_provisioned_volume_over_nfs",
      ),
    ],
  },
  Capability {
    name: "Mount a volume on Windows",
    status: Status::Limited,
    r#where: "Windows (WinFsp)",
    limits: "proven for create, write, read, list and delete on the CI runner",
    evidence: &[ev(
      "crates/bridge-winfsp/tests/mount.rs",
      "a_real_winfsp_mount_serves_a_volume_through_the_windows_filesystem",
    )],
  },
  Capability {
    name: "Land a volume to disk under a human grant",
    status: Status::Works,
    r#where: "macOS, Linux",
    limits: "grants come only from the CLI or a confirmation surface; MCP and the SDKs cannot grant (R10)",
    evidence: &[
      ev(
        "crates/server/tests/daemon.rs",
        "a_grant_is_accepted_only_with_a_verified_proof_bound_to_the_presented_landing",
      ),
      ev(
        "crates/server/tests/daemon.rs",
        "a_granted_landing_consumes_its_presentation",
      ),
      ev(
        "crates/server/tests/snapshot_landing.rs",
        "a_landing_of_a_snapshot_writes_its_bytes_and_the_head_lands_after_it",
      ),
    ],
  },
  Capability {
    name: "Merge: greens, work volumes, submit, rebase",
    status: Status::Works,
    r#where: "one machine and the fleet",
    limits: "—",
    evidence: &[
      ev(
        "crates/server/tests/daemon.rs",
        "the_merge_service_enforces_roles_pins_versions_and_seals_behind_the_barrier",
      ),
      ev(
        "crates/cli/tests/cli.rs",
        "the_verbs_emit_json_with_the_json_flag",
      ),
    ],
  },
  Capability {
    name: "Acknowledged content survives a daemon restart",
    status: Status::Works,
    r#where: "macOS, Linux",
    limits: "a restart under the same anchor; the anchor's own death loses RAM by design",
    evidence: &[ev(
      "crates/server/tests/recovery.rs",
      "acknowledged_content_and_its_snapshot_survive_a_daemon_restart_byte_for_byte",
    )],
  },
  Capability {
    name: "MCP server for agents (`slates mcp`)",
    status: Status::Works,
    r#where: "stdio everywhere; loopback HTTP on macOS and Linux",
    limits: "no landing grant over MCP (R10)",
    evidence: &[ev(
      "crates/mcp/tests/mcp.rs",
      "the_mcp_surface_serves_the_tools",
    )],
  },
  Capability {
    name: "Python SDK, sync and async",
    status: Status::Works,
    r#where: "macOS, Linux, Windows (selector loop)",
    limits: "not yet published to PyPI",
    evidence: &[
      ev(
        "crates/sdk-python/tests/test_sdk.py",
        "test_lifecycle_round_trip_over_a_live_daemon",
      ),
      ev(
        "crates/sdk-python/tests/test_sdk_async.py",
        "test_every_async_call_ends_across_restart_silence_cancellation_and_death",
      ),
    ],
  },
  Capability {
    name: "Node SDK, sync and async",
    status: Status::Works,
    r#where: "macOS, Linux, Windows",
    limits: "not yet published to npm",
    evidence: &[
      ev(
        "crates/sdk-node/tests/sdk.test.mjs",
        "lifecycle round trip over a live daemon",
      ),
      ev(
        "crates/sdk-node/tests/sdk_async.test.mjs",
        "every async call ends across restart, silence, reader loss and death",
      ),
    ],
  },
  Capability {
    name: "Fleet: replication, takeover, multi-process deployment",
    status: Status::Limited,
    r#where: "macOS, Linux",
    limits: "consensus heartbeats share their coordinator with bulk work (AUD-29-28); the transport is being replaced by a conformed QUIC (AUD-29-50–54)",
    evidence: &[
      ev(
        "crates/cli/tests/cli.rs",
        "three_daemon_processes_deploy_a_fleet_from_one_manifest_and_survive_the_owners_death",
      ),
      ev(
        "crates/server/tests/fleet.rs",
        "a_provisioned_head_replicates_across_the_fleet",
      ),
    ],
  },
  Capability {
    name: "Containers: an OCI runtime binds a volume",
    status: Status::Limited,
    r#where: "Linux",
    limits: "the host attachment is bound into the container; a served FUSE export and live source authority are owed (AUD-29-64–67)",
    evidence: &[ev(
      "crates/cli/tests/cli.rs",
      "an_oci_container_consumes_the_host_attachment_through_the_runtime_bind",
    )],
  },
  Capability {
    name: "VM guests over virtio-fs",
    status: Status::Limited,
    r#where: "a simulated guest driver",
    limits: "no real VMM binding yet (AUD-29-68–73)",
    evidence: &[ev(
      "crates/server/tests/virtiofs.rs",
      "a_guest_writes_a_file_into_a_daemon_volume_that_the_host_reads_back_over_nfs",
    )],
  },
  Capability {
    name: "Locked residency (`--locked`): pinned, unswappable volume memory",
    status: Status::Owed,
    r#where: "—",
    limits: "`--locked` records the intent only (AUD-29-77)",
    evidence: &[],
  },
];

/// The README table rendered from the registry, markers included.
pub fn render() -> String {
  let mut out = String::new();
  out.push_str(BEGIN);
  out.push('\n');
  out.push_str("| Capability | Status | Where | Limits | Proven by |\n|---|---|---|---|---|\n");
  for row in CAPABILITIES {
    let proof = if row.evidence.is_empty() {
      "—".to_owned()
    } else {
      row
        .evidence
        .iter()
        .map(|evidence| format!("`{}` ({})", evidence.test, evidence.file))
        .collect::<Vec<_>>()
        .join("<br>")
    };
    out.push_str(&format!(
      "| {} | {} | {} | {} | {} |\n",
      row.name,
      row.status.label(),
      row.r#where,
      row.limits,
      proof
    ));
  }
  out.push_str(END);
  out
}

/// The README's table block, markers included, if it has one.
fn readme_block(readme: &str) -> Option<&str> {
  let start = readme.find(BEGIN)?;
  let end = readme
    .get(start..)?
    .find(END)?
    .checked_add(start)?
    .checked_add(END.len())?;
  readme.get(start..end)
}

/// Every reason the registry or the README is out of step (empty when in step).
pub fn problems(root: &Path) -> Vec<String> {
  let mut problems = Vec::new();
  for row in CAPABILITIES {
    match row.status {
      Status::Works | Status::Limited if row.evidence.is_empty() => {
        problems.push(format!(
          "capability `{}` claims to work but cites no test",
          row.name
        ));
      }
      Status::Owed if !row.limits.contains("AUD-") && !row.limits.contains("GAP") => {
        problems.push(format!("owed capability `{}` names no gap", row.name));
      }
      _ => {}
    }
    for evidence in row.evidence {
      if let Some(problem) = evidence_problem(root, evidence) {
        problems.push(format!("capability `{}`: {problem}", row.name));
      }
    }
  }
  match std::fs::read_to_string(root.join("README.md")) {
    Ok(readme) => match readme_block(&readme) {
      Some(block) if block == render() => {}
      Some(_) => problems.push(
        "README.md's capability table differs from the registry; run `cargo xtask capabilities --write`"
          .to_owned(),
      ),
      None => problems.push("README.md has no capability table markers".to_owned()),
    },
    Err(error) => problems.push(format!("README.md: {error}")),
  }
  problems
}

/// Why `evidence` is not a runnable test in the tree, if it is not.
fn evidence_problem(root: &Path, evidence: &Evidence) -> Option<String> {
  let source = match std::fs::read_to_string(root.join(evidence.file)) {
    Ok(source) => source,
    Err(_) => return Some(format!("{} does not exist", evidence.file)),
  };
  let declaration = if evidence.file.ends_with(".rs") {
    format!("fn {}(", evidence.test)
  } else if evidence.file.ends_with(".py") {
    format!("def {}(", evidence.test)
  } else {
    format!("test('{}'", evidence.test)
  };
  let Some(at) = source.find(&declaration) else {
    return Some(format!(
      "{} declares no test `{}`",
      evidence.file, evidence.test
    ));
  };
  if evidence.file.ends_with(".rs") {
    // The attributes directly above the function: `#[test]` must be there, `#[ignore]` must not.
    let above = source.get(..at).unwrap_or("");
    let attributes: Vec<&str> = above
      .lines()
      .rev()
      .skip_while(|line| line.trim().is_empty())
      .take_while(|line| {
        let line = line.trim();
        line.starts_with("#[") || line.starts_with("///") || line.starts_with("//")
      })
      .collect();
    if !attributes.iter().any(|line| line.trim() == "#[test]") {
      return Some(format!(
        "`{}` in {} is not a #[test]",
        evidence.test, evidence.file
      ));
    }
    if attributes
      .iter()
      .any(|line| line.trim().starts_with("#[ignore"))
    {
      return Some(format!(
        "`{}` in {} is #[ignore]d",
        evidence.test, evidence.file
      ));
    }
  }
  None
}

/// Rewrites the README's table from the registry.
pub fn write(root: &Path) -> Result<(), String> {
  let path = root.join("README.md");
  let readme = std::fs::read_to_string(&path).map_err(|e| format!("README.md: {e}"))?;
  let block = readme_block(&readme).ok_or("README.md has no capability table markers")?;
  let updated = readme.replacen(block, &render(), 1);
  // The development tool rewriting the tree's own README (not a host path of the product).
  #[allow(clippy::disallowed_methods)]
  std::fs::write(&path, updated).map_err(|e| format!("README.md: {e}"))
}

#[cfg(test)]
mod tests {
  use super::*;

  /// AUD-29-32. Do: check the registry against the tree. Expect: every cited test exists, is a test and
  /// is not ignored, and every owed row names its gap — the same check `cargo xtask check` runs, minus the
  /// README comparison.
  #[test]
  fn every_cited_test_exists_and_runs() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap();
    let problems: Vec<String> = problems(root)
      .into_iter()
      .filter(|problem| !problem.starts_with("README.md"))
      .collect();
    assert!(problems.is_empty(), "{problems:#?}");
  }

  /// AUD-29-32. Do: point a row at a test that does not exist, and at one that is ignored. Expect: both
  /// reported, so a renamed, removed or ignored proof cannot keep a capability looking proven.
  #[test]
  fn a_missing_or_ignored_proof_is_reported() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap();
    let missing = ev("crates/cli/tests/cli.rs", "no_such_test_anywhere");
    assert!(evidence_problem(root, &missing).is_some());
    let ignored = ev(
      "crates/cluster/tests/publication_cost.rs",
      "a_publication_costs_the_clone_the_encoding_and_the_hash_of_the_whole_state",
    );
    assert!(evidence_problem(root, &ignored).unwrap().contains("ignore"));
  }
}
